package webui

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

// assets contains the production UI generated by Vite.
//
//go:embed assets
var assets embed.FS

type handler struct {
	files http.Handler
	root  fs.FS
}

// Handler serves the embedded local application and falls back to index.html
// for client-side routes. API paths are deliberately outside this handler.
func Handler() http.Handler {
	root, err := fs.Sub(assets, "assets")
	if err != nil {
		panic(err)
	}
	return handler{files: http.FileServer(http.FS(root)), root: root}
}

func (h handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("X-Frame-Options", "DENY")
	w.Header().Set("Referrer-Policy", "no-referrer")
	w.Header().Set("Content-Security-Policy", "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'")

	requested := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
	if requested == "." || requested == "" {
		w.Header().Set("Cache-Control", "no-store")
		h.files.ServeHTTP(w, r)
		return
	}
	if _, err := fs.Stat(h.root, requested); err != nil && path.Ext(requested) == "" {
		w.Header().Set("Cache-Control", "no-store")
		clone := r.Clone(r.Context())
		clone.URL.Path = "/"
		h.files.ServeHTTP(w, clone)
		return
	}
	if strings.HasPrefix(requested, "assets/") {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	}
	h.files.ServeHTTP(w, r)
}
