const headerBytes = 4;
export const maximumFrameBytes = 12 * 1024 * 1024;
export const maximumResourceBytes = 5 * 1024 * 1024;
export const maximumRenderedHTMLBytes = 4 * 1024 * 1024;
export const maximumScreenshotBytes = 2 * 1024 * 1024;

export interface BrowserDiagnostic { readonly level:string; readonly message:string; }
export interface ResourceFailure { readonly resourceType:string; readonly url:string; readonly errorCode:string; }
export interface AccessibilityFinding { readonly ruleId:string; readonly impact:string; readonly tags:readonly string[]; readonly target:string; readonly html:string; readonly help:string; }

export interface RenderRequest { readonly kind:"render_request"; readonly protocolVersion:1; readonly requestId:string; readonly url:string; readonly deadlineMs:number; readonly maximumRequests:number; readonly maximumBytes:number; readonly captureScreenshot?:boolean; readonly runAccessibility?:boolean; }
export interface FetchResourceRequest { readonly kind:"fetch_resource"; readonly protocolVersion:1; readonly requestId:string; readonly fetchId:string; readonly url:string; readonly resourceType:string; }
export interface FetchResourceResponse { readonly kind:"fetch_resource_result"; readonly protocolVersion:1; readonly requestId:string; readonly fetchId:string; readonly status:"completed"|"blocked"|"failed"; readonly statusCode?:number; readonly headers?:Record<string,string>; readonly bodyBase64?:string; readonly errorCode?:string; }
export interface RenderResponse { readonly kind:"render_result"; readonly protocolVersion:1; readonly requestId:string; readonly status:"completed"|"blocked"|"failed"; readonly html?:string; readonly finalURL?:string; readonly requestCount:number; readonly transferredBytes:number; readonly errorCode?:string; readonly screenshotBase64?:string; readonly screenshotTruncated?:boolean; readonly viewport?:string; readonly engineVersion?:string; readonly consoleMessages?:readonly BrowserDiagnostic[]; readonly resourceFailures?:readonly ResourceFailure[]; readonly accessibility?:readonly AccessibilityFinding[]; }
export type SupervisorMessage = RenderRequest|FetchResourceResponse;
export type WorkerMessage = FetchResourceRequest|RenderResponse;

export function validateRenderRequest(value:unknown):RenderRequest{if(!value||typeof value!=="object")throw new TypeError("render request must be an object");const item=value as Record<string,unknown>;const keys=new Set(["kind","protocolVersion","requestId","url","deadlineMs","maximumRequests","maximumBytes","captureScreenshot","runAccessibility"]);if(Object.keys(item).some(key=>!keys.has(key)))throw new TypeError("render request contains unknown fields");if(item.kind!=="render_request"||item.protocolVersion!==1||typeof item.requestId!=="string"||item.requestId.length<1||item.requestId.length>200||typeof item.url!=="string"||!/^https?:\/\//.test(item.url)||!Number.isInteger(item.deadlineMs)||Number(item.deadlineMs)<100||Number(item.deadlineMs)>120_000||!Number.isInteger(item.maximumRequests)||Number(item.maximumRequests)<1||Number(item.maximumRequests)>2_000||!Number.isInteger(item.maximumBytes)||Number(item.maximumBytes)<1_024||Number(item.maximumBytes)>100*1024*1024||(item.captureScreenshot!==undefined&&typeof item.captureScreenshot!=="boolean")||(item.runAccessibility!==undefined&&typeof item.runAccessibility!=="boolean"))throw new TypeError("render request is invalid or outside budgets");return item as unknown as RenderRequest;}
export function encodeFrame(value:unknown):Uint8Array{const payload=Buffer.from(JSON.stringify(value),"utf8");if(payload.byteLength>maximumFrameBytes)throw new RangeError("renderer frame exceeds the maximum size");const frame=Buffer.allocUnsafe(headerBytes+payload.byteLength);frame.writeUInt32BE(payload.byteLength,0);payload.copy(frame,headerBytes);return frame;}
export class FrameDecoder{#buffer=Buffer.alloc(0);push(chunk:Uint8Array):unknown[]{this.#buffer=Buffer.concat([this.#buffer,chunk]);const values:unknown[]=[];while(this.#buffer.byteLength>=headerBytes){const length=this.#buffer.readUInt32BE(0);if(length>maximumFrameBytes){this.#buffer=Buffer.alloc(0);throw new RangeError("renderer frame exceeds the maximum size");}if(this.#buffer.byteLength<headerBytes+length)break;const payload=this.#buffer.subarray(headerBytes,headerBytes+length);values.push(JSON.parse(payload.toString("utf8")) as unknown);this.#buffer=this.#buffer.subarray(headerBytes+length);}return values;}}
